import Head from "next/head";
import Link from "next/link";
import { SignInButton, SignOutButton, UserButton } from "@clerk/nextjs";
import { useUser } from "@clerk/nextjs";

import { api } from "~/utils/api";

export default function Home() {
  const user = useUser();

  const { data } = api.posts.getAll.useQuery();

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex h-screen justify-center">
        <div className="w-full border-x border-slate-400 md:max-w-2xl">
          <div className="flex justify-between border-b border-slate-400 bg-slate-800 p-4">
            <UserButton afterSignOutUrl="/" />
            {user.isSignedIn ? <SignOutButton /> : <SignInButton />}
          </div>
          <div className="p-4">
            {data?.map((post) => <div key={post.id}>{post.content}</div>)}
          </div>
        </div>
      </main>
    </>
  );
}
